### ISSUE TITLE
Hud Configuration

### ISSUE THREAD

**Issue by timkrieger** [GreatOrator/TolkienCraft-3-Map#10]
## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: forge-1.10.2-12.18.3.2281
* TolkienCraft II version: 0.9.5

vanilla armor bar hides the vanilla health bar in default hud configuration when you are wearing armor
  - workaround by going into mod options -> RPG-hud -> config -> debug settings -> player armor -> prevent event : ON

**Comment by GreatOrator** [comment]
Aye, I forgot to add the files RPGHUD uses after I arranged everything in my gui.  Will be included in the next pack update and hopefully by then he will also have the placement piece implemented which will allow me to manually arrange where everything sits in the hud.

**Comment by GreatOrator** [comment]
Should be fixed next update.
