### ISSUE TITLE
Glorfindel I - quest reward

### ISSUE THREAD

**Issue by timkrieger** [GreatOrator/TolkienCraft-3-Map#11]
## Description
The Wisdom of Lord Glorfindel I - quest completes but needed item for next quest not received ( Beryl ).

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version:
* TolkienCraft II version: 0.9.5
* java version "1.8.0_121"
Running linux multiplayer server and linux clients

Having issues with the Lord Glorfindel quest line, have made several attempts with new world recreations to test, each time the quest line appears to work fine up to this point.

While trying to debug the issue I noticed that the starting quest that sets the scoreboard had not completed, not sure if that is related or a seperate symptom / issue.

**Comment by GreatOrator** [comment]
Currently working out that one...have not yet found the cause of the quest to not trigger correctly even though it does on the dev server all the time.

**Comment by GreatOrator** [comment]
Alright, found the fix.  Will be implemented in next update. thank you for reporting :D
