### ISSUE TITLE
2 Dolmed Way

### ISSUE THREAD

**Issue by timkrieger** [GreatOrator/TolkienCraft-3-Map#12]
## Description
purchase of house does not remove iron door

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: 12.18.3.2281
* TolkienCraft II version: 0.9.6

In the Eriador player housing area by rivendel house :  2 Dolmed Way.

After purchasing the key and taking the key and clicking on the box by the house, the ownership sign shows up but the iron door did not disappear.

**Comment by GreatOrator** [comment]
Thank you, will test it out to confirm and fix the schematic if that is the case.

**Comment by GreatOrator** [comment]
I found out why, had the location for the replacement off by a block.  Should be fixed next time I post an update to the map.
