### ISSUE TITLE
Deep Dark Portal - Eriador

### ISSUE THREAD

**Issue by timkrieger** [GreatOrator/TolkienCraft-3-Map#13]
## Description
Enter the deep dark from the Eriador player area, when returning you are dropped into the middle of the ocean in the overworld.  Co-ordinates look correct for the Eriador portal, just wrong dimension.

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: 
* TolkienCraft II version: 0.9.6

**Comment by GreatOrator** [comment]
That's not a bug, it is a feature.  The deep dark portal always dumps players back in the overworld unfortunately, very similar to how you can't enter the nether through a genuine portal in any dimension but overworld, nothing can be done about it sadly.
