### ISSUE TITLE
Missing Ore Generation?

### ISSUE THREAD

**Issue by timkrieger** [GreatOrator/TolkienCraft-3-Map#14]
Possibly a bug, possibly just not implemented yet...

We have been playing through the map and mined out a bunch of the deep dark but have been unable to find Vinteum for Ars Magica or Apatite for Forestry.   Have not found Cactus or a green dye substitute ( woot mob prism )

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: 12.18.3.2281
* TolkienCraft II version: 0.9.6

**Comment by GreatOrator** [comment]
I'll take a look, that is very possible.

**Comment by timkrieger** [comment]
Confirmed that Vinteum and Apatite spawn in the world as of 12.2.

Unable to find cactus or any of the ars magica flowers in the world ( have been able to get a few from beyond the player dimension barrier )

**Comment by GreatOrator** [comment]
Cactus is plentiful in the southern desert, the ars flowers I am working on just have not got to the merchants yet, there is an issue open for the main pack that lists items planned to be in merchants.

**Comment by GreatOrator** [comment]
This should now be fixed/addressed so closing.
