### ISSUE TITLE
BQ Quests not advancing on their own

### ISSUE THREAD

**Issue by timkrieger** [GreatOrator/TolkienCraft-3-Map#16]
The Quests in the BetterQuesting book do not progress on their own, each step that has a detection piece needs to have the detect/submit button in the quest book pressed.

Not a huge issue for most quests as you can click the button to move things along, but it breaks all the hidden quests.  Only after clicking on the detect/submit button in creative mode does the quest auto-complete.

EG :  Launching a new game world and starting from the initial spawn location, moving to the map location for the "Welcome to Middle Earth" quest.  Opening the quest book and looking at the quest it shows as undiscovered in the quest book.  This does not change until clicking on the detect button.  After which the location goes to found, and roughly 1 second later the quest auto-completes ( claim button grey's out ).

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: 12.18.3.2281
* TolkienCraft II version: 0.10.1

java version :  1.8.0_121"
running on Linux MultiMC

**Comment by GreatOrator** [comment]
Talk to the NPC in rivendell (the record keeper) book is in edit mode and he has an option to turn it off

**Comment by timkrieger** [comment]
Spoke with Darage the record keeper, the option to reload BQ Quests did
not have any affect, there were a couple placeholder items in his
dialogs that may have been the option you were speaking of.

I did find the command to switch edit mode off from the betterquesting
wiki and once getting the quest book out of edit mode { /bq_admin edit
}  It did indeed correct the quest issues and they progress as
expected.




On Thu, 2017-05-11 at 12:42 -0700, GreatOrator wrote:
> > Talk to the NPC in rivendell (the record keeper) book is in edit mode
and he has an option to turn it off
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 
>   
>   
> 
> 
> 
> 
> 
> 
> > > > > > > > > > > > > > > {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
5493e4bb","name":"GitHub"},"entity":{"external_key":"github/GreatOrat
or/TolkienCraft-3-Map","title":"GreatOrator/TolkienCraft-3-
Map","subtitle":"GitHub repository","main_image_url":"https://cloud.g
ithubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-
7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent
.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
b52498112777.png","action":{"name":"Open in
GitHub","url":"https://github.com/GreatOrator/TolkienCraft-3-
Map"}},"updates":{"snippets":[{"icon":"PERSON","message":"@GreatOrato
r in #16: Talk to the NPC in rivendell (the record keeper) book is in
edit mode and he has an option to turn it
off\r\n"}],"action":{"name":"View
Issue","url":"https://github.com/GreatOrator/TolkienCraft-3-
Map/issues/16#issuecomment-300896182"}}}
