### ISSUE TITLE
Possible Player Housing Issue

### ISSUE THREAD

**Issue by timkrieger** [GreatOrator/TolkienCraft-3-Map#17]
Eriador Player Housing dimension

1 Tawarwaith Place
 - NW corner of main floor has door to a basement, basement is full of dirt otherwise structure is complete ( walls, lighting, etc ).

2 - Dolmed Way & 4 - Dolmed Way
 - cold cellar under the kitchen is full of dirt, otherwise structure is complete and full of goodies!

Checked the other player housing dimensions, the above three appear to be the only houses that have an under ground room.

**Comment by GreatOrator** [comment]
Yeah, it's a product of the import process of the house, as long as the houses are usable at this point it is not a priority, though I will note it for fixing at some point.

**Comment by GreatOrator** [comment]
Fixed the first one, though decided to leave the other two, if there are gifts, you must work for them :D
