### ISSUE TITLE
Crash due to storage drawers

### ISSUE THREAD

**Issue by DarkwingDuckie** [GreatOrator/TolkienCraft-3-Map#23]
Random recent occurrence where the game will crash on start up giving me this crash report

```
[crash-2017-07-04_02.19.30-client.txt](https://github.com/GreatOrator/TolkienCraft-3-Map/files/1144139/crash-2017-07-04_02.19.30-client.txt)

```

**Comment by GreatOrator** [comment]
After all of the recent updates have been unable to replicate to marking fixed and closing issue
