### ISSUE TITLE
Ars Magica Arcane Compendium issues

### ISSUE THREAD

**Issue by timkrieger** [GreatOrator/TolkienCraft-3-Map#29]
Portions of the Arcane Compendium are not readable

open arcane compendium.
select Blocks -> obelisk, turn to page showing obelisk with upgrades ( page 4 ) 

obelisk pages past this point are broken, ( unable to get to rituals for upgrading obelisk )

note :  stand next to a wall when opening the book, on page 4 a draconic advanced stabalizer appears over player.

TolkienCraft III : Patreon test server

**Comment by GreatOrator** [comment]
Does this still happen?

**Comment by timkrieger** [comment]
tested today on the 13.1 patreon server, the advanced stabalizer no longer appears over my player, the pages of the compendium after page 4 show with no content other than page title.  Clicking to change layer page 6 locks up the minecraft client.

**Comment by GreatOrator** [comment]
can you somehow get me the forge log? it may have some info as to what is happening

**Comment by timkrieger** [comment]
Log from client.  Many errors while page 4 of obelisk is open in the compendium.
[log.zip](https://github.com/GreatOrator/TolkienCraft-3-Map/files/1347373/log.zip)

**Comment by GreatOrator** [comment]
Thank you, I can see the error and it is probably because ars is not fully compatible with recent versions of forge now.  I'll try to see if they are even still updating, but I worry that this is not the case any longer.
