### ISSUE TITLE
Player Dimension Issue

### ISSUE THREAD

**Issue by timkrieger** [GreatOrator/TolkienCraft-3-Map#32]
When leaving the Rhovanian player dimension the portal takes you to the outside of the player dimension at Rivendel.

Tolkiencraft server download 13.1

**Comment by timkrieger** [comment]
Confirmed the same on the Patreon Server.

**Comment by GreatOrator** [comment]
If all goes well should have a map update to fix that and will get on the server to get it addressed on it's own since I do not want to reset player housing. Thanks for letting me know and sorry for the delay in responding...been really busy at home though saw when you first posted.

**Comment by GreatOrator** [comment]
Fixed, should be in update today and fixed on player server.
