### ISSUE TITLE
Tolkiencraft III download and install maps issues

### ISSUE THREAD

**Issue by Michael-McKinley** [GreatOrator/TolkienCraft-3-Map#4]
## Description
I just installed TolkienCraft III from the Curse Launcher. When I selected the "Download and Install maps" I got a screen that had "Something Went Wrong" in red at the top and indicated the path to the MadHelpSplashScreen..json file was wrong (two dots are correct for the message, please see the attached screen shot)
![minecraft 1 10 2 4_7_2017 12_08_11 pm](https://cloud.githubusercontent.com/assets/5976433/24815705/fd8b62b2-1b8a-11e7-8659-430c99971711.png)

Also all links for the maps are directed to the following:
www.somedirectdownload.com/map.zip
Which is a camped domain from squatters and serves up no maps.

I found the reference to the first URL in the ...\config\brandon3055\madhelp\madhelp.cfg file
the reference to the MadHelpContentList.jason is also there. I found the MadHelpContentList in your GitHub directory at https://github.com/GreatOrator/TolkienCraft-3-Map, but was not able to locate the Splash Screen file anywhere. And the links to the www.somedirectdownload.com/map.zip are all in the Content List file.

I am assuming that since this is still not the full release version (0.9.1), that these items are on the To-Do list already but wanted to report them just in case.

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: (did not check, it is what was installed by the Curse Launcher for this pack)
* TolkienCraft II version: TolkienCraft III 0.9.1  

## Crash report
```
CRASH REPORT HERE
```

**Comment by GreatOrator** [comment]
They are default because the map is not ready for public consumption yet which is mentioned on the curse page. But thank you for paying attention :D
