### ISSUE TITLE
Better Questing - Aid of Mirkwood II

### ISSUE THREAD

**Issue by scopius** [GreatOrator/TolkienCraft-3-Map#41]
## Description
In BQ, I have completed the Location Task for the Aid of Mirkwood II quest.  The other quest system (MCA? Custom NPCs? It's the one that defaults to the L key), shows no quests in this quest line, as they were completed.  Elrond, however, won't talk to me, except for saying Hello.  Is there a workaround for when something like this happens, maybe bu going into Edit mode for BQ.  I don't want to break the whole questline, not sure if this is a danger, or how to edit a quest to mark it complete?  If that is what I want?  I just want Elrond to talk to me!  Thank you.

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: 12.18.3.2511
* TolkienCraft II version: 1.1.7

## Crash report
```
CRASH REPORT HERE
```

**Comment by GreatOrator** [comment]
if I remember correctly, you have to go speak to legolas in the guest house in rivendell to proceed

**Comment by scopius** [comment]
Actually, I had to finish speaking to Elrond's son.  You evidently have to speak to him again after the first convo.  Thank you for your reply.
